on:
  pull_request_target:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.title }}
      - name: install wkhtmltopdf & fonts
        run: sudo apt-get install wkhtmltopdf fonts-noto-cjk
      - name: html to pdf
        run: wkhtmltopdf --enable-local-file-access index.html index.pdf
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: index.pdf
          tag_name: ${{ github.event.pull_request.title }}
          draft: true
          prerelease: true
